spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/LocalDB
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

resilience:
  application-name: Resilience - Local