spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://prod-server:3306/ProdDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: true
server:
  port: 8080

resilience:
  application-name: Resilience - Prod