spring:
  application:
    name: Resilience
  profiles:
    active: local
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.hibernate: ERROR
    org.springdoc: DEBUG

resilience:
  application-name: Resilience
  default-accent-color: "#009688"