spring:
  application:
    name: Resilience
  profiles:
    active: local
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.hibernate: ERROR
    org.springdoc: DEBUG

resilience:
  application-name: Resilience
  default-accent-color: "#009688"